import 'package:pflege_lock_app/core/models/question.dart';

List<Question> getSeedQuestions() {
  return [
    // fachbegriff (1-20)
    const Question(
      category: 'fachbegriff',
      promptDe: 'Herr Müller hat blaue Flecken am Rücken',
      correctAnswer: 'Hämatombildung',
      wrongOpt1: 'Wundnekrose',
      wrongOpt2: 'Petechien',
      wrongOpt3: 'Erythem',
      explanation: 'Ein Hämatom ist eine Blutansammlung im Gewebe nach Gefäßverletzung.',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Die Wunde riecht unangenehm',
      correctAnswer: 'Fötider Wundgeruch / Hinweis auf Wundinfektion',
      wrongOpt1: 'Granulationsgewebe',
      wrongOpt2: 'Serom',
      wrongOpt3: 'Epithelisierung',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Frau Schmidt kann nicht schlucken',
      correctAnswer: 'Dysphagie',
      wrongOpt1: 'Dysarthrie',
      wrongOpt2: 'Aphasie',
      wrongOpt3: 'Dyspnoe',
      explanation: 'Dysphagie = Schluckstörung. Wichtig: Aspirationsprophylaxe!',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat Schwierigkeiten beim Atmen',
      correctAnswer: 'Dyspnoe',
      wrongOpt1: 'Tachykardie',
      wrongOpt2: 'Zyanose',
      wrongOpt3: 'Orthopnoe',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Die Haut des Patienten ist gelblich',
      correctAnswer: 'Ikterus',
      wrongOpt1: 'Zyanose',
      wrongOpt2: 'Erythem',
      wrongOpt3: 'Vitiligo',
      explanation: 'Ikterus = Gelbfärbung durch Bilirubinerhöhung, oft bei Leber-/Gallenerkrankungen.',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat Wassereinlagerungen in den Beinen',
      correctAnswer: 'Periphere Ödeme',
      wrongOpt1: 'Thrombose',
      wrongOpt2: 'Hämatom',
      wrongOpt3: 'Lipödem',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Frau Braun kann ihren linken Arm nicht bewegen',
      correctAnswer: 'Hemiparese / Hemiplegie links',
      wrongOpt1: 'Ataxie',
      wrongOpt2: 'Tremor',
      wrongOpt3: 'Spastik',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat Durchfall',
      correctAnswer: 'Diarrhö',
      wrongOpt1: 'Obstipation',
      wrongOpt2: 'Meteorismus',
      wrongOpt3: 'Flatulenz',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient erbricht sich wiederholt',
      correctAnswer: 'Emesis / rezidivierendes Erbrechen',
      wrongOpt1: 'Hämatemesis',
      wrongOpt2: 'Regurgitation',
      wrongOpt3: 'Nausea',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat starken Schwindel',
      correctAnswer: 'Vertigo',
      wrongOpt1: 'Synkope',
      wrongOpt2: 'Ataxie',
      wrongOpt3: 'Nystagmus',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Die Wunde zeigt rosa, körniges Gewebe',
      correctAnswer: 'Granulationsgewebe',
      wrongOpt1: 'Fibrinbelag',
      wrongOpt2: 'Nekrose',
      wrongOpt3: 'Mazeration',
      explanation: 'Granulationsgewebe ist ein gutes Zeichen — die Wunde heilt.',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient spricht unverständlich / verwaschen',
      correctAnswer: 'Dysarthrie',
      wrongOpt1: 'Aphasie',
      wrongOpt2: 'Dysphagie',
      wrongOpt3: 'Mutismus',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Frau Meier uriniert sehr häufig, aber nur wenig',
      correctAnswer: 'Pollakisurie',
      wrongOpt1: 'Polyurie',
      wrongOpt2: 'Oligurie',
      wrongOpt3: 'Strangurie',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat Fieber über 38,5 Grad',
      correctAnswer: 'Hyperthermie / Fieber',
      wrongOpt1: 'Hypothermie',
      wrongOpt2: 'Subfebrile Temperatur',
      wrongOpt3: 'Sepsis',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Die Haut ist trocken, rissig und schuppt sich',
      correctAnswer: 'Xerosis cutis',
      wrongOpt1: 'Intertrigo',
      wrongOpt2: 'Dermatitis',
      wrongOpt3: 'Psoriasis',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient klagt über brennenden Schmerz beim Wasserlassen',
      correctAnswer: 'Dysurie',
      wrongOpt1: 'Pollakisurie',
      wrongOpt2: 'Hämaturie',
      wrongOpt3: 'Anurie',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient ist kaum wach zu bekommen',
      correctAnswer: 'Somnolenz / Bewusstseinstrübung',
      wrongOpt1: 'Koma',
      wrongOpt2: 'Synkope',
      wrongOpt3: 'Lethargie',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Frau Schmidt ist verwirrt und weiß nicht, wo sie ist',
      correctAnswer: 'Desorientiertheit / Orientierungsstörung',
      wrongOpt1: 'Demenz',
      wrongOpt2: 'Delir',
      wrongOpt3: 'Amnesie',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Die Wundränder liegen aufeinander, kein Infektzeichen',
      correctAnswer: 'Primäre Wundheilung (per primam intentionem)',
      wrongOpt1: 'Sekundärheilung',
      wrongOpt2: 'Granulationsphase',
      wrongOpt3: 'Fibrinbelag',
    ),
    const Question(
      category: 'fachbegriff',
      promptDe: 'Der Patient hat Blut im Urin',
      correctAnswer: 'Hämaturie',
      wrongOpt1: 'Proteinurie',
      wrongOpt2: 'Glukosurie',
      wrongOpt3: 'Pyurie',
    ),
    // berechnung (21-30)
    const Question(
      category: 'berechnung',
      promptDe: '500ml Infusion über 4 Stunden. Tropfzahl: 20 gtt/ml. Wie viele Tropfen/min?',
      correctAnswer: '42 gtt/min',
      wrongOpt1: '25 gtt/min',
      wrongOpt2: '50 gtt/min',
      wrongOpt3: '33 gtt/min',
      explanation: 'Formel: (500 × 20) / (4 × 60) = 41,6 ≈ 42 gtt/min',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Patient wiegt 80kg. Dosis: 5mg/kg/Tag in 2 Einzeldosen. Wie viel mg pro Gabe?',
      correctAnswer: '200mg',
      wrongOpt1: '400mg',
      wrongOpt2: '100mg',
      wrongOpt3: '250mg',
    ),
    const Question(
      category: 'berechnung',
      promptDe: '1000ml NaCl 0,9% über 8 Stunden. Wie viel ml/Stunde?',
      correctAnswer: '125 ml/h',
      wrongOpt1: '100 ml/h',
      wrongOpt2: '150 ml/h',
      wrongOpt3: '80 ml/h',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Normaler Blutzucker nüchtern — welcher Bereich in mmol/L?',
      correctAnswer: '3,9 – 5,5 mmol/L',
      wrongOpt1: '6,0 – 8,0 mmol/L',
      wrongOpt2: '2,0 – 3,5 mmol/L',
      wrongOpt3: '5,6 – 7,0 mmol/L',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Patient: 170cm, 85kg. Was ist sein BMI und wie wird er eingeordnet?',
      correctAnswer: 'BMI 29,4 — Präadipositas',
      wrongOpt1: 'BMI 25,0 — Normalgewicht',
      wrongOpt2: 'BMI 31,5 — Adipositas Grad I',
      wrongOpt3: 'BMI 27,0 — Normalgewicht',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Atemfrequenz des Patienten: 22/min. Wie ist das zu bewerten?',
      correctAnswer: 'Tachypnoe — erhöht (Normwert Erwachsene: 12–18/min)',
      wrongOpt1: 'Bradypnoe',
      wrongOpt2: 'Normalbefund',
      wrongOpt3: 'Hyperventilation',
    ),
    const Question(
      category: 'berechnung',
      promptDe: '250ml Infusion über 2h mit Infusionspumpe. Wie viel ml/h?',
      correctAnswer: '125 ml/h',
      wrongOpt1: '100 ml/h',
      wrongOpt2: '250 ml/h',
      wrongOpt3: '50 ml/h',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Optimaler systolischer Blutdruck beim Erwachsenen?',
      correctAnswer: '< 120 mmHg (optimal)',
      wrongOpt1: '< 90 mmHg',
      wrongOpt2: '130–139 mmHg',
      wrongOpt3: '≥ 140 mmHg',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'Patient trinkt: 250ml Tee, 150ml Wasser, 300ml Suppe. Einfuhr gesamt?',
      correctAnswer: '700 ml',
      wrongOpt1: '500 ml',
      wrongOpt2: '650 ml',
      wrongOpt3: '750 ml',
    ),
    const Question(
      category: 'berechnung',
      promptDe: 'SpO2 91% gemessen. Wie ist das einzuordnen?',
      correctAnswer: 'Hypoxämie — Handlungsbedarf, Arzt informieren',
      wrongOpt1: 'Normalbefund',
      wrongOpt2: 'Leichte Abweichung, nur beobachten',
      wrongOpt3: 'Hyperoxie',
    ),
    // pflegeplanung (31-40)
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Welches Pflegeproblem hat ein Patient mit Dekubitus Grad II?',
      correctAnswer: 'Chronische Wunde mit Hautdefekt — Risiko für Wundinfektion und verzögerte Heilung',
      wrongOpt1: 'Infektionsgefahr durch Blasenkatheter',
      wrongOpt2: 'Sturzgefahr',
      wrongOpt3: 'Mangelernährung',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Was ist die ERSTE Maßnahme beim Sturz eines Patienten?',
      correctAnswer: 'Sturzsituation sichern, Patient nicht sofort bewegen, Arzt informieren',
      wrongOpt1: 'Patient sofort aufheben und ins Bett legen',
      wrongOpt2: 'Vitalzeichen messen',
      wrongOpt3: 'Angehörige anrufen',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Welches Assessmentinstrument wird für das Dekubitusrisiko verwendet?',
      correctAnswer: 'Braden-Skala',
      wrongOpt1: 'Barthel-Index',
      wrongOpt2: 'NRS 2002',
      wrongOpt3: 'Glasgow Coma Scale',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'ATL steht für?',
      correctAnswer: 'Aktivitäten des täglichen Lebens (nach Juchli/Roper)',
      wrongOpt1: 'Ärztliche Therapieleistung',
      wrongOpt2: 'Allgemeine Therapieleistung',
      wrongOpt3: 'Aktive Transferleistung',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'ABEDL steht für?',
      correctAnswer: 'Aktivitäten, Beziehungen und existenzielle Erfahrungen des Lebens (nach Krohwinkel)',
      wrongOpt1: 'Allgemeine Bedarfserfassung der Lebenssituation',
      wrongOpt2: 'Ärztliche Behandlungsdokumentation',
      wrongOpt3: 'Aktivitäten, Bewegung und Ernährung des Lebens',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Welcher DNQP-Expertenstandard befasst sich mit Sturzprävention?',
      correctAnswer: 'Expertenstandard Sturzprophylaxe in der Pflege',
      wrongOpt1: 'Expertenstandard Dekubitusprophylaxe',
      wrongOpt2: 'Expertenstandard Schmerzmanagement',
      wrongOpt3: 'Expertenstandard Ernährungsmanagement',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Was bedeutet Kinästhetik in der Pflege?',
      correctAnswer: 'Konzept zur Unterstützung von Bewegung und Transfer durch gezielte Wahrnehmungsschulung',
      wrongOpt1: 'Passive Krankengymnastik',
      wrongOpt2: 'Lagern zur Dekubitusprophylaxe',
      wrongOpt3: 'Atemtherapie nach Bobath',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Was braucht man rechtlich für eine Fixierung / freiheitsentziehende Maßnahme?',
      correctAnswer: 'Genehmigung durch das Betreuungsgericht (§1906 BGB) — ärztliche Anordnung allein reicht nicht',
      wrongOpt1: 'Nur ärztliche Anordnung ist ausreichend',
      wrongOpt2: 'Pflegefachkraft entscheidet selbst',
      wrongOpt3: 'Angehörige müssen schriftlich zustimmen',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Was ist ein Pflegebericht?',
      correctAnswer: 'Pflegerische Verlaufsdokumentation: Beobachtungen, Maßnahmen und Reaktionen des Patienten',
      wrongOpt1: 'Ärztlicher Übergabebericht',
      wrongOpt2: 'Medizinische Diagnosestellung',
      wrongOpt3: 'Abrechnungsbeleg der Pflegekasse',
    ),
    const Question(
      category: 'pflegeplanung',
      promptDe: 'Was bedeutet Prophylaxe in der Pflege?',
      correctAnswer: 'Vorbeugende Pflegemaßnahme zur Verhinderung möglicher Pflegeprobleme',
      wrongOpt1: 'Behandlung bestehender Erkrankungen',
      wrongOpt2: 'Rehabilitative Maßnahme',
      wrongOpt3: 'Beobachtung ohne Intervention',
    ),
    // anatomie (41-50)
    const Question(
      category: 'anatomie',
      promptDe: 'Wo liegt das Herz im Körper?',
      correctAnswer: 'Im Mediastinum, leicht nach links versetzt (ca. 2/3 links, 1/3 rechts)',
      wrongOpt1: 'Vollständig in der rechten Thoraxhälfte',
      wrongOpt2: 'Zentral hinter dem Sternum',
      wrongOpt3: 'Vollständig links',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Welche Herzregion pumpt sauerstoffreiches Blut in den Körperkreislauf?',
      correctAnswer: 'Linke Herzkammer (linker Ventrikel)',
      wrongOpt1: 'Rechte Herzkammer',
      wrongOpt2: 'Linkes Vorhof',
      wrongOpt3: 'Rechter Vorhof',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Wo wird Insulin produziert?',
      correctAnswer: 'In den Langerhans-Inseln der Bauchspeicheldrüse (Pankreas)',
      wrongOpt1: 'In der Leber',
      wrongOpt2: 'In der Nebenniere',
      wrongOpt3: 'In der Hypophyse',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Welcher Nerv steuert das Zwerchfell (Hauptatemmuskel)?',
      correctAnswer: 'Nervus phrenicus',
      wrongOpt1: 'Nervus vagus',
      wrongOpt2: 'Nervus radialis',
      wrongOpt3: 'Nervus medianus',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Normaler Atemfrequenz-Bereich beim Erwachsenen?',
      correctAnswer: '12 – 18 Atemzüge pro Minute',
      wrongOpt1: '18 – 25 pro Minute',
      wrongOpt2: '8 – 12 pro Minute',
      wrongOpt3: '20 – 30 pro Minute',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Was ist die Hauptaufgabe der Niere?',
      correctAnswer: 'Blutfiltration, Urinproduktion und Regulation des Wasser-/Elektrolythaushalts',
      wrongOpt1: 'Blutbildung (Hämatopoese)',
      wrongOpt2: 'Ausschließlich Hormonproduktion',
      wrongOpt3: 'Fettstoffwechsel',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Wo findet der Gasaustausch in der Lunge statt?',
      correctAnswer: 'In den Alveolen (Lungenbläschen) — Sauerstoff rein, CO2 raus',
      wrongOpt1: 'In der Trachea',
      wrongOpt2: 'In den Hauptbronchien',
      wrongOpt3: 'Im Pleuraraum',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Welche Funktionen hat die Leber?',
      correctAnswer: 'Entgiftung, Galleproduktion, Proteinsynthese und Glykogenspeicher',
      wrongOpt1: 'Blutfiltration wie die Niere',
      wrongOpt2: 'Sauerstoffproduktion',
      wrongOpt3: 'Insulinproduktion',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Normwert Körpertemperatur rektal beim Erwachsenen?',
      correctAnswer: '36,5 – 37,5 °C',
      wrongOpt1: '35,0 – 36,0 °C',
      wrongOpt2: '38,0 – 39,0 °C',
      wrongOpt3: '37,5 – 38,5 °C',
    ),
    const Question(
      category: 'anatomie',
      promptDe: 'Wo wird Blut mit Sauerstoff angereichert (oxygeniert)?',
      correctAnswer: 'In der Lunge — Gasaustausch an den Alveolen mit den Kapillaren',
      wrongOpt1: 'Im Herz',
      wrongOpt2: 'In der Leber',
      wrongOpt3: 'Im Knochenmark',
    ),
  ];
}

Future<void> seedDatabaseIfNeeded(
  Future<void> Function(Question q) insertQuestion,
) async {
  // Seeding is orchestrated by DatabaseHelper with SharedPreferences check.
  for (final q in getSeedQuestions()) {
    await insertQuestion(q);
  }
}
